/**
 * POST /api/generate/form-1301 — Field-code-mapped PDF overlay
 *
 * Form 1301 (2025) is a 4-page static PDF. Coordinates come from
 * `templates/maps/1301_2025.json`, auto-generated by
 * `scripts/build-field-map.mjs` — see the form-135 route for full
 * architecture commentary and the 135_1301 generation task.md spec.
 *
 * Pass { "calibrate": true } to overlay red `→key:code` labels for
 * visual verification.
 */

import type { NextRequest } from "next/server";
import { PDFDocument, PDFFont, StandardFonts, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import fs from "fs";
import path from "path";
import { buildForm1301Fields, hebrewForPdf, assertForm1301Consistency } from "@/lib/pdfUtils";
import { isValidTZ } from "@/lib/validateTZ";
import { loadFieldMap, findField, type FieldMap } from "@/lib/fieldMap";
import { withUser } from "@/lib/api/withUser";
import { auditLog } from "@/lib/audit/auditEvents";
import { withRateLimitForUser } from "@/lib/api/withRateLimit";
import {
  invalidInput,
  invalidInputFromZod,
  internalError,
  serviceUnavailable,
} from "@/lib/api/errorEnvelope";
import { Form1301PayloadSchema } from "@/lib/api/schemas/generate";

const FORM_ID       = "1301_2025";
const TEMPLATE_PATH = path.join(process.cwd(), "public/templates/form1301_2025.pdf");
const FONT_TTF      = path.join(process.cwd(), "public/fonts/Assistant-Regular.ttf");
const FONT_WOFF     = path.join(process.cwd(), "public/fonts/Assistant-Regular.woff2");

const TEXT_COLOR = rgb(0.05, 0.2, 0.7); // readable navy blue
const CAL_COLOR  = rgb(0.9, 0, 0);

// ── Draw-list spec (mirror of form-135's structure) ─────────────────────────
//
// Phase 1 §1.D introduced parity with Form 135's coverage regime:
//   - DRAW_LIST_1301:        coordinate-anchored stamps (resolved via field-map).
//   - POSITIONAL_DRAWS_1301: stamps the auto-scanner could not anchor (page-3
//                            spouse-name continuation, page-4 signature/date).
//   - EXCLUDED_CODES_1301:   codes in `templates/maps/1301_2025.json` that are
//                            intentionally NOT stamped at runtime, each with a
//                            one-line justification. Enforced by the coverage
//                            regression test `form1301Coverage.test.ts`.

export interface FieldDraw {
  key:     string;
  /** Value-key read from `buildForm1301Fields(...)`. Stored on the draw entry
   *  so the coverage test can validate `DRAW_LIST_1301` statically without
   *  invoking the engine. */
  valueKey: string;
  code:    string;
  column?: string | null;
  size?:   number;
  heb?:    boolean;
  align?:  "right" | "left";
}

export const DRAW_LIST_1301: ReadonlyArray<FieldDraw> = [
  // ── Personal section ──────────────────────────────────────────────────────
  // page-3 ID duplicates: 278 (taxpayer ID) + 277 (spouse ID).
  { key: "taxpayerId278", valueKey: "012",     code: "278", size: 10, align: "right" },
  { key: "spouseId277",   valueKey: "013",     code: "277", size: 10, align: "right" },
  // page-1 / page-2 personal block.
  { key: "idPersonal",    valueKey: "012",     code: "012", size: 10, align: "right" },
  { key: "lastName",      valueKey: "032",     code: "032", size: 10, heb: true, align: "left" },
  { key: "city",          valueKey: "022",     code: "022", size: 10, heb: true, align: "left" },
  { key: "street",        valueKey: "023",     code: "023", size: 10, heb: true, align: "left" },
  { key: "houseNumber",   valueKey: "024",     code: "024", size: 10, align: "right" },

  // ── Employment — main vs 2nd employer columns (codes carry separate slots) ─
  { key: "grossSalaryMain", valueKey: "158_main", code: "158", size: 11, align: "right" },
  { key: "grossSalary2nd",  valueKey: "172_2nd",  code: "172", size: 11, align: "right" },
  { key: "taxWithheldMain", valueKey: "068_main", code: "068", size: 11, align: "right" },
  { key: "taxWithheld2nd",  valueKey: "069_2nd",  code: "069", size: 11, align: "right" },
  { key: "pensionMain",     valueKey: "258_main", code: "258", size: 10, align: "right" },
  { key: "severance",       valueKey: "272",      code: "272", size: 10, align: "right" },

  // ── Business income ───────────────────────────────────────────────────────
  { key: "bizIncomeMain", valueKey: "201", code: "201", size: 11, align: "right" },
  { key: "bizIncome2nd",  valueKey: "301", code: "301", size: 11, align: "right" },

  // ── Capital gains ────────────────────────────────────────────────────────
  { key: "capitalGainRight",  valueKey: "060",       code: "060", size: 11, align: "right" },
  { key: "capitalGainCenter", valueKey: "211",       code: "211", size: 11, align: "right" },
  { key: "capitalLoss",       valueKey: "067",       code: "067", size: 11, align: "right" },
  { key: "foreignTaxCode157", valueKey: "157",       code: "157", size: 10, align: "right" },
  { key: "foreignTaxCode055", valueKey: "055_1301",  code: "055", size: 10, align: "right" },
  { key: "otherIncome",       valueKey: "141",       code: "141", size: 10, align: "right" },

  // ── Deductions — page 1 ──────────────────────────────────────────────────
  { key: "donations",       valueKey: "078", code: "078", size: 10, align: "right" },
  { key: "lifeInsurance",   valueKey: "126", code: "126", size: 10, align: "right" },
  { key: "indPension",      valueKey: "142", code: "142", size: 10, align: "right" },
  { key: "totalDeductions", valueKey: "335", code: "335", size: 10, align: "right" },

  // ── Deductions — page 3/4 (ITA p1↔p3 cross-check) ────────────────────────
  { key: "lifeInsP3",          valueKey: "036_p3", code: "036", size: 10, align: "right" },
  { key: "pensionDeductionP3", valueKey: "045_p3", code: "045", size: 10, align: "right" },
  { key: "donationsP3",        valueKey: "037_p3", code: "037", size: 10, align: "right" },

  // ── Bank details (page 3 footer) ─────────────────────────────────────────
  { key: "bankNumber",    valueKey: "274", code: "274", size: 10, align: "right" },
  { key: "branchNumber",  valueKey: "273", code: "273", size: 10, align: "right" },
  { key: "accountNumber", valueKey: "044", code: "044", size: 10, align: "right" },
];

/**
 * Positional draws — fields the user must see on the form whose anchor codes
 * are NOT present in the auto-generated `templates/maps/1301_2025.json` (the
 * code label was filtered as a section reference, or the cell has no printed
 * code at all). Coordinates calibrated against the 2025 template.
 *
 * NOTE: the multi-employer overflow page (added at `pdfDoc.addPage(...)` when
 * 3+ secondary employers exist) is handled INLINE in the route handler — it is
 * NOT a positional draw against the static template. Same for the tax-year
 * overlay (white-rectangle + redraw at the page-1 header).
 */
export interface PositionalDraw {
  key: string;
  valueKey: string;
  /** ITA code the field corresponds to (for documentation + test cross-ref). */
  code: string;
  /** pdf-lib 0-indexed page. */
  page: number;
  /** pdf-lib bottom-left x. */
  x: number;
  /** pdf-lib bottom-left y. */
  y: number;
  size?: number;
  heb?: boolean;
  /** Set to true if the value is a Hebrew word/phrase needing BiDi shaping. */
  reverse?: boolean;
}

export const POSITIONAL_DRAWS_1301: ReadonlyArray<PositionalDraw> = [
  // 031 — first name. The auto-scanner did not detect a 3-digit "031" code
  // near the first-name value-box on the 1301 (the form labels it with the
  // Hebrew "שם פרטי" text only). Coordinates source: page-1 personal row,
  // mirroring the first-name slot on Form 135.
  { key: "firstName031", valueKey: "031", code: "031", page: 0, x: 360, y: 700, size: 9, heb: true, reverse: true },

  // 015 — תאריך עליה (DD/MM/YYYY). Page-1 residency row.
  { key: "aliyahDate015", valueKey: "aliyahDate", code: "015", page: 0, x: 50, y: 56, size: 9 },

  // 016 — תושב יישוב מזכה. Page-1 residency-row checkbox.
  { key: "peripheryFlag016", valueKey: "peripheryFlag", code: "016", page: 0, x: 280, y: 56, size: 10 },

  // 119 — זיכוי בגין בן/בת זוג (count). Page-2 credit-points panel slot.
  { key: "spouseCredit119", valueKey: "spouseCreditPoints", code: "119", page: 1, x: 305, y: 360, size: 9 },

  // 245 — נקודות זיכוי בגין ילדים (count). Page-2 credit-points panel slot.
  { key: "childCreditPoints245", valueKey: "245", code: "245", page: 1, x: 250, y: 360, size: 9 },

  // 086 — מענק פטור (Sec. 9(7א)). Page-2 severance row.
  { key: "exemptGrant086", valueKey: "086", code: "086", page: 1, x: 200, y: 280, size: 10 },

  // 117 — דיבידנד / 124 — ריבית ני"ע סחירים. The 1301 has these on page 2;
  // the auto-scanner did detect them in the field-map (covered by DRAW_LIST
  // via the 117 / 124 entries on the 135 → 1301 inheritance), so they are
  // already drawn through the regular draw-list when present in `vals`.

  // Page-4 signature block (text only, NOT a digital signature). Phase 0 §0.D
  // delivered the equivalent on Form 135; mirror here so SHAAM intake does
  // not flag the 1301 as unsigned.
  { key: "signatureName_p4", valueKey: "signatureName", code: "signature-block", page: 3, x: 100, y: 80, size: 10, heb: true, reverse: true },
  { key: "signatureDate_p4", valueKey: "signatureDate", code: "signature-block", page: 3, x: 280, y: 80, size: 10 },

  // Declaration checkbox (page 4) — "אני מצהיר שכל הפרטים נכונים…". Stamp X.
  { key: "declarationMark_p4", valueKey: "declarationMark", code: "declaration-checkbox", page: 3, x: 470, y: 110, size: 12 },
];

/**
 * Codes that exist in `templates/maps/1301_2025.json` but are intentionally
 * NOT stamped at runtime. Each entry MUST carry a one-line justification.
 *
 * Categories:
 *   - "spouse-column": spouse-attributed mirrors (`*_registered_spouse`,
 *     `*_spouse`, `040_col_2`). Phase 1 §1.A wires the spouse-side data.
 *   - "computation-row": ITA-scanner-derived sub-totals that the filer must
 *     not stamp (the ITA back-office computes them from primary fields).
 *   - "phase-1": fields whose source data is not yet available in the
 *     TaxPayer / FinancialData model; deferred to a later 1.* sub-task.
 *   - "form-internal": SHAAM-internal scanner reference codes.
 *   - "multi-employer-column": secondary-employer column slots on page 1
 *     beyond the 2nd employer (the 3rd, 4th, ... are emitted as the
 *     in-route overflow annex page, not positional stamps on the template).
 *   - "out-of-scope": fields belonging to a section the product does not
 *     yet collect (e.g. business expenses sub-rows on page 2 of the 1301
 *     when the user reports business income through Form 6111 instead).
 */
export const EXCLUDED_CODES_1301: Readonly<Record<string, string>> = {
  // ── Spouse-column mirrors (column-keyed) ────────────────────────────────
  "040_registered_spouse": "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "040_spouse":            "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "040_col_2":             "spouse-column — Phase 1 §1.A spouse-secondary-employer",
  "042_registered_spouse": "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "042_spouse":            "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "043_registered_spouse": "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "043_spouse":            "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "260_registered_spouse": "spouse-column — Phase 1 §1.A spouse-data plumbing",
  "260_spouse":            "spouse-column — Phase 1 §1.A spouse-data plumbing",

  // ── Computation rows / sub-totals (page 1) ──────────────────────────────
  "100": "computation-row — page-1 income subtotal, derived by ITA scanner",
  "107": "computation-row — page-1 income subtotal, derived",
  "108": "computation-row — page-1 income subtotal, derived",
  "109": "computation-row — page-1 income subtotal, derived",
  "111": "computation-row — page-1 calc sub-total, derived",
  "112": "computation-row — page-1 calc sub-total, derived",
  "113": "computation-row — page-1 calc sub-total, derived",
  "115": "computation-row — page-1 calc sub-total, derived",
  "118": "computation-row — page-1 calc sub-total, derived",
  "120": "computation-row — page-1 calc sub-total, derived",
  "121": "computation-row — page-1 calc sub-total, derived",
  "122": "computation-row — page-1 calc sub-total, derived",
  "123": "computation-row — page-1 calc sub-total, derived",
  "129": "computation-row — page-1 calc sub-total, derived",
  "132": "computation-row — page-1 calc sub-total, derived",
  "136": "computation-row — page-1 calc sub-total, derived",
  "137": "computation-row — page-1 calc sub-total, derived",
  "139": "computation-row — page-1 calc sub-total, derived",
  "140": "computation-row — page-1 calc sub-total, derived",
  "148": "computation-row — page-1 calc sub-total, derived",
  "151": "computation-row — page-1 calc sub-total, derived",
  "153": "computation-row — page-1 calc sub-total, derived",
  "155": "computation-row — page-1 calc sub-total, derived",
  "159": "computation-row — page-1 calc sub-total, derived",
  "160": "computation-row — page-1 calc sub-total, derived",
  "163": "computation-row — page-1 calc sub-total, derived",
  "165": "computation-row — page-1 calc sub-total, derived",
  "166": "computation-row — page-1 capital-loss duplicate (drawn at code 067)",
  "167": "computation-row — page-1 sub-total, derived",
  "168": "computation-row — page-1 sub-total, derived",
  "173": "computation-row — page-1 sub-total, derived",
  "174": "computation-row — page-1 sub-total, derived",
  "179": "computation-row — page-1 sub-total, derived",
  "180": "computation-row — page-1 sub-total, derived",
  "182": "computation-row — page-1 sub-total, derived",
  "183": "computation-row — page-1 sub-total, derived",
  "184": "computation-row — page-1 sub-total, derived",
  "185": "computation-row — page-1 sub-total, derived",
  "186": "computation-row — page-1 sub-total, derived",
  "187": "computation-row — page-1 sub-total, derived",
  "190": "computation-row — page-1 partial-year months",
  "194": "computation-row — page-1 sub-total, derived",
  "195": "computation-row — page-1 sub-total, derived",
  "196": "computation-row — page-1 sub-total, derived",
  "199": "computation-row — page-1 sub-total, derived",
  "202": "computation-row — page-2 business sub-total, derived",
  "204": "computation-row — page-2 business sub-total, derived",
  "205": "computation-row — page-2 business sub-total, derived",
  "206": "computation-row — page-2 business sub-total, derived",
  "207": "computation-row — page-2 business sub-total, derived",
  "209": "computation-row — page-2 business sub-total, derived",
  "212": "computation-row — page-2 sub-total, derived",
  "213": "computation-row — page-2 sub-total, derived",
  "214": "computation-row — page-2 sub-total, derived",
  "217": "computation-row — page-2 sub-total, derived",
  "220": "computation-row — page-2 sub-total, derived",
  "222": "computation-row — page-2 sub-total, derived",
  "225": "computation-row — page-2 sub-total, derived",
  "226": "computation-row — page-2 sub-total, derived",
  "227": "computation-row — page-2 sub-total, derived",
  "228": "computation-row — page-2 sub-total, derived",
  "232": "computation-row — page-2 sub-total, derived",
  "235": "computation-row — page-2 sub-total, derived",
  "236": "computation-row — page-2 sub-total, derived",
  "237": "computation-row — page-2 sub-total, derived",
  "238": "computation-row — page-2 sub-total, derived",
  "239": "computation-row — page-2 sub-total, derived",
  "240": "computation-row — page-2 sub-total, derived",
  "241": "computation-row — page-2 sub-total, derived",
  "242": "computation-row — page-2 sub-total, derived",
  "250": "computation-row — page-2 secondary-employer net, derived",
  "255": "computation-row — page-2 sub-total, derived",
  "256": "computation-row — page-2 capital-gain duplicate (drawn at code 060)",
  "257": "computation-row — page-2 sub-total, derived",
  "259": "computation-row — page-2 sub-total, derived",
  "262": "computation-row — page-2 sub-total, derived",
  "263": "computation-row — page-2 sub-total, derived",
  "268": "computation-row — page-2 sub-total, derived",
  "269": "computation-row — page-2 sub-total, derived",
  "270": "computation-row — page-2 sub-total, derived",
  "271": "computation-row — page-2 sub-total, derived",
  "275": "computation-row — page-3 sub-total, derived",
  "276": "computation-row — page-3 sub-total, derived",
  "279": "computation-row — page-3 sub-total, derived",
  "284": "computation-row — page-3 sub-total, derived",
  "285": "computation-row — page-3 sub-total, derived",
  "286": "computation-row — page-3 sub-total, derived",
  "287": "computation-row — page-3 sub-total, derived",
  "288": "computation-row — page-3 sub-total, derived",
  "290": "computation-row — page-3 sub-total, derived",
  "291": "computation-row — page-3 sub-total, derived",
  "292": "computation-row — page-3 sub-total, derived",
  "294": "computation-row — page-3 sub-total, derived",
  "295": "computation-row — page-3 sub-total, derived",
  "296": "computation-row — page-3 sub-total, derived",
  "299": "computation-row — page-3 sub-total, derived",
  "302": "computation-row — page-3 sub-total, derived",
  "304": "computation-row — page-3 sub-total, derived",
  "305": "computation-row — page-3 sub-total, derived",
  "307": "computation-row — page-3 sub-total, derived",
  "309": "computation-row — page-3 sub-total, derived",
  "311": "computation-row — page-3 sub-total, derived",
  "312": "computation-row — page-3 sub-total, derived",
  "313": "computation-row — page-3 sub-total, derived",
  "314": "computation-row — page-3 sub-total, derived",
  "317": "computation-row — page-3 sub-total, derived",
  "319": "computation-row — page-3 sub-total, derived",
  "323": "computation-row — page-3 sub-total, derived",
  "324": "computation-row — page-3 sub-total, derived",
  "325": "computation-row — page-3 sub-total, derived",
  "326": "computation-row — page-3 sub-total, derived",
  "327": "computation-row — page-3 sub-total, derived",
  "328": "computation-row — page-3 sub-total, derived",
  "331": "computation-row — page-3 sub-total, derived",
  "332": "computation-row — page-4 footer total, derived",
  "336": "computation-row — page-4 sub-total, derived",
  "337": "computation-row — page-4 sub-total, derived",
  "338": "computation-row — page-4 sub-total, derived",
  "339": "computation-row — page-4 sub-total, derived",
  "340": "computation-row — page-4 sub-total, derived",
  "341": "computation-row — page-4 sub-total, derived",
  "342": "computation-row — page-4 sub-total, derived",
  "343": "computation-row — page-4 sub-total, derived",
  "344": "computation-row — page-4 sub-total, derived",
  "345": "computation-row — page-4 sub-total, derived",
  "346": "computation-row — page-4 sub-total, derived",
  "347": "computation-row — page-4 sub-total, derived",
  "350": "computation-row — page-4 sub-total, derived",
  "351": "computation-row — page-4 sub-total, derived",
  "352": "computation-row — page-4 sub-total, derived",
  "357": "computation-row — page-4 sub-total, derived",
  "358": "computation-row — page-4 sub-total, derived",
  "361": "computation-row — page-4 sub-total, derived",
  "362": "computation-row — page-4 sub-total, derived",
  "363": "computation-row — page-4 sub-total, derived",
  "364": "computation-row — page-4 sub-total, derived",
  "365": "computation-row — page-4 sub-total, derived",
  "366": "computation-row — page-4 sub-total, derived",
  "367": "computation-row — page-4 sub-total, derived",
  "369": "computation-row — page-4 sub-total, derived",
  "370": "computation-row — page-4 sub-total, derived",
  "372": "computation-row — page-4 sub-total, derived",
  "441": "computation-row — page-4 footer total",
  "442": "computation-row — page-4 footer total",
  "443": "computation-row — page-4 footer total",

  // ── Phase-1 / out-of-scope source data ───────────────────────────────────
  "005": "phase-1 — page-1 form-version code; auto-set by ITA",
  "006": "phase-1 — page-1 sub-classification flag; not in TaxPayer model",
  "011": "phase-1 — phone (mobile) capture; Phase 1 §1.A questionnaire add",
  "014": "phase-1 — תושב ישראל לכל השנה Y/N (single-cell on 1301); Phase 1 §1.A",
  "020": "phase-1 — מצב משפחתי checkbox row; Phase 1 §1.A spouse-column completion",
  "021": "phase-1 — birthDate field; auto-scanned coords need recalibration",
  "025": "phase-1 — תושב חוזר flag; Phase 1 §1.A returning-resident",
  "026": "phase-1 — marital-status sub-row; Phase 1 §1.A",
  "028": "phase-1 — alternate residency reason; Phase 1 §1.A",
  "029": "phase-1 — alternate residency reason; Phase 1 §1.A",
  "030": "phase-1 — pension type subdivision",
  "034": "phase-1 — page-1 secondary-residence flag",
  "036": "computation-row — page-1 life-insurance duplicate (drawn at p3 via code 036)",
  "038": "phase-1 — credit-point sub-classification box",
  "041": "phase-1 — page-1 secondary-employer hours flag",
  "045": "computation-row — page-1 pension duplicate (drawn at p3 via code 045)",
  "046": "phase-1 — page-1 severance type-1 sub-classification",
  "048": "phase-1 — page-1 severance type-2 sub-classification",
  "050": "computation-row — page-1 capital-gain net subtotal (drawn at code 060)",
  "051": "phase-1 — page-1 capital-gain sub-classification",
  "052": "phase-1 — page-1 capital-gain sub-classification",
  "054": "computation-row — page-2 sub-total, derived",
  "056": "phase-1 — page-1 reserve-currency capital-gain",
  "059": "phase-1 — page-1 capital-gain sub-classification",
  "061": "phase-1 — page-1 capital-gain sub-classification",
  "065": "phase-1 — page-1 trust capital-gain",
  "077": "phase-1 — page-1 deduction sub-classification",
  "079": "phase-1 — page-1 donation type-2",
  "080": "phase-1 — page-1 donation type-3",
  "081": "phase-1 — life-insurance sub-classification",
  "082": "phase-1 — pension sub-classification",
  "083": "phase-1 — page-1 deduction sub-classification",
  "084": "phase-1 — page-1 deduction sub-classification",
  "085": "phase-1 — page-1 deduction sub-classification",
  "087": "phase-1 — page-1 disability deduction",
  "088": "phase-1 — page-1 footer Yes/No row",
  "089": "phase-1 — page-1 footer Yes/No row",
  "092": "phase-1 — page-2 alternate-income classification",
  "096": "phase-1 — page-2 footer Yes/No row",
  "097": "phase-1 — page-2 alternate-income classification",
  "117": "phase-1 — דיבידנד; 1301 page-2 (engine surfaces \"\" today; 1.K IBKR split)",
  "124": "phase-1 — ריבית ני\"ע סחירים; engine surfaces \"\" today; 1.K IBKR split",
  "126": "computation-row — page-1 life-insurance duplicate (drawn at p3 via code 036)",
  "142": "computation-row — page-1 individual-pension duplicate (drawn via 045_p3)",
  "170": "phase-1 — page-1 secondary-employer column gross",
  "218": "phase-1 — קה\"ש חייבת חלק מעסיק (Form 106 expansion needed; 1.C)",
  "219": "phase-1 — קה\"ש חייבת חלק עובד (Form 106 expansion needed; 1.C)",
  "244": "phase-1 — קה\"ש פטורה (Form 106 expansion needed; 1.C)",
  "245": "phase-1 — נקודות זיכוי בגין ילדים (positional draw covers 1301 page-2)",
  "248": "phase-1 — קה\"ש חייבת חלק מעסיק; Form 106 expansion (1.C)",
  "249": "phase-1 — קה\"ש חייבת חלק עובד; Form 106 expansion (1.C)",
  "086": "phase-1 — מענק פטור Sec 9(7א) (positional draw covers 1301 page-2)",

  // ── Form-internal / SHAAM scanner reference ──────────────────────────────
  "702": "form-internal — SHAAM scanner reference, never stamped by filer",
  "858": "form-internal — SHAAM scanner reference, never stamped by filer",
};

async function handle(req: NextRequest, ctx: { uid: string; requestId: string }): Promise<Response> {
  if (!fs.existsSync(TEMPLATE_PATH)) {
    return serviceUnavailable(
      "תבנית הטופס אינה זמינה כרגע.",
      "TEMPLATE_MISSING",
    );
  }

  let raw: unknown;
  try {
    raw = await req.json();
  } catch {
    return invalidInput("גוף הבקשה אינו JSON תקין.");
  }
  const parsedBody = Form1301PayloadSchema.safeParse(raw);
  if (!parsedBody.success) {
    return invalidInputFromZod(parsedBody.error.issues, "פורמט הבקשה אינו תקין.");
  }
  const body = parsedBody.data;

  try {
    // The Zod schema validates structure + bounds. The output types are a
    // structural subset of TaxPayer/FinancialData (insights/actionItems are
    // accepted as `unknown[]` since we don't render their internals in the
    // PDF), so we cast back to the canonical app types.
    const taxpayer = body.taxpayer as unknown as import("@/types").TaxPayer;
    const financials = body.financials as unknown as import("@/types").FinancialData;

    if (taxpayer.idNumber && !isValidTZ(taxpayer.idNumber)) {
      return invalidInput("מספר תעודת זהות לא תקין — ספרת ביקורת שגויה");
    }

    const calibrate = !!body.calibrate;

    const map: FieldMap = loadFieldMap(FORM_ID);
    const pdfDoc = await PDFDocument.load(fs.readFileSync(TEMPLATE_PATH), { ignoreEncryption: true });

    const pageCount = pdfDoc.getPageCount();
    if (pageCount < 4) {
      return internalError(
        "תבנית הטופס פגומה. צור קשר עם התמיכה.",
        `Form 1301 template has ${pageCount} pages (expected 4).`,
      );
    }

    pdfDoc.registerFontkit(fontkit);
    const fontPath   = fs.existsSync(FONT_TTF) ? FONT_TTF : FONT_WOFF;
    const hebrewFont = await pdfDoc.embedFont(fs.readFileSync(fontPath), { subset: false });
    const latinBold  = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const latinReg   = await pdfDoc.embedFont(StandardFonts.Helvetica);

    console.log(
      `[form-1301] template=${path.basename(TEMPLATE_PATH)} pages=${pageCount} ` +
      `map_codes=${Object.keys(map.fields).length} calibrate=${calibrate}`,
    );

    const vals = buildForm1301Fields(taxpayer, financials);

    const issues = assertForm1301Consistency(vals);
    if (issues.length > 0) {
      console.warn("[form-1301] page 1/3 deduction mismatch:", issues);
      if (calibrate) {
        return new Response(
          JSON.stringify({ error: { code: "DEDUCTION_MISMATCH", message: "אי-התאמה בין סכומי ניכויים בעמוד 1 ובעמוד 3.", details: { issues } } }),
          { status: 422, headers: { "Content-Type": "application/json; charset=utf-8" } },
        );
      }
    }

    // Helper: resolve a draw's text from buildForm1301Fields output. The
    // valueKey indirection lets the coverage test validate DRAW_LIST_1301
    // statically without invoking the engine.
    const valueFor = (
      key: string,
      heb: boolean | undefined,
    ): string => {
      const v = (vals as unknown as Record<string, string | undefined>)[key] ?? "";
      return heb ? hebrewForPdf(v) : v;
    };

    const pageHeight = map.page_size.height;
    const drawn: { key: string; code: string; page: number }[] = [];
    const missing: string[] = [];

    // ── Coordinate-anchored draws (resolved through the field-code map) ──────
    for (const d of DRAW_LIST_1301) {
      const text = valueFor(d.valueKey, d.heb);
      if (!text || text === "0") continue;

      const field = findField(map, d.code, d.column);
      if (!field) {
        missing.push(`${d.key}(${d.code})`);
        continue;
      }

      const page = pdfDoc.getPage(field.page - 1);
      const font: PDFFont = d.heb ? hebrewFont : latinBold;
      const size = d.size ?? 10;

      const yBaseline = pageHeight - field.value_box.y_bottom + 2;
      let x = field.value_box.x_left + 2;
      if ((d.align ?? "right") === "right") {
        const width = font.widthOfTextAtSize(text, size);
        x = field.value_box.x_right - width - 2;
      }

      try {
        page.drawText(text, { x, y: yBaseline, font, size, color: TEXT_COLOR });
        drawn.push({ key: d.key, code: d.code, page: field.page });
      } catch (e) {
        console.warn(`[form-1301] field "${d.key}"(${d.code}): ${e instanceof Error ? e.message : e}`);
      }

      if (calibrate) {
        try {
          page.drawText(`→${d.key}:${d.code}`, {
            x: field.value_box.x_left, y: yBaseline + size + 1,
            font: latinReg, size: 6, color: CAL_COLOR,
          });
        } catch { /* non-critical */ }
      }
    }

    // ── Positional draws (codes the auto-scanner could not anchor) ────────────
    for (const p of POSITIONAL_DRAWS_1301) {
      const text = valueFor(p.valueKey, p.reverse);
      if (!text) continue;
      if (p.page < 0 || p.page >= pdfDoc.getPageCount()) continue;

      const page = pdfDoc.getPage(p.page);
      const font: PDFFont = p.heb ? hebrewFont : latinBold;
      const size = p.size ?? 10;
      try {
        page.drawText(text, { x: p.x, y: p.y, font, size, color: TEXT_COLOR });
        drawn.push({ key: p.key, code: p.code, page: p.page + 1 });
      } catch (e) {
        console.warn(`[form-1301] positional "${p.key}"(${p.code}): ${e instanceof Error ? e.message : e}`);
      }

      if (calibrate) {
        try {
          page.drawText(`→${p.key}:${p.code}`, {
            x: p.x, y: p.y + size + 1,
            font: latinReg, size: 6, color: CAL_COLOR,
          });
        } catch { /* non-critical */ }
      }
    }

    // ── Tax-year header overlay ───────────────────────────────────────────────
    if (vals.taxYear) {
      const page1 = pdfDoc.getPage(0);
      page1.drawRectangle({ x: 191, y: 816, width: 42, height: 14, color: rgb(1, 1, 1), borderWidth: 0 });
      page1.drawText(vals.taxYear, { x: 193, y: 820, font: latinBold, size: 10, color: TEXT_COLOR });
    }

    // ── Multi-employer overflow sheet (3+ secondary employers) ────────────────
    const secondaryEmployers = (taxpayer.employers ?? []).filter((e) => !e.isMainEmployer);
    if (secondaryEmployers.length >= 2) {
      const overflow = pdfDoc.addPage([595.275, 841.89]);
      const rows = secondaryEmployers.map((e, i) => ({
        idx: i + 2,
        name: e.name ?? "",
        months: e.monthsWorked ?? 0,
        gross: e.grossSalary ?? 0,
        tax: e.taxWithheld ?? 0,
        pension: e.pensionDeduction ?? 0,
        pensionFund: e.pensionFundName ?? "",
      }));
      overflow.drawText(hebrewForPdf("פירוט מעסיקים נוספים — נספח לטופס 1301"),
        { x: 60, y: 800, font: hebrewFont, size: 14, color: TEXT_COLOR });
      overflow.drawText(
        `Tax year: ${vals.taxYear}   |   ID: ${vals["012"] || "-"}`,
        { x: 60, y: 780, font: latinReg, size: 10, color: TEXT_COLOR },
      );
      const colHeaders = ["#", "Name", "Months", "Gross (ILS)", "Tax (ILS)", "Pension (ILS)", "Pension Fund"];
      const colX = [60, 90, 260, 310, 380, 450, 520];
      colHeaders.forEach((h, ci) => {
        overflow.drawText(h, { x: colX[ci], y: 745, font: latinBold, size: 9, color: TEXT_COLOR });
      });
      rows.forEach((r, ri) => {
        const y = 725 - ri * 16;
        overflow.drawText(String(r.idx),              { x: colX[0], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(hebrewForPdf(r.name),       { x: colX[1], y, font: hebrewFont, size: 9, color: TEXT_COLOR });
        overflow.drawText(String(r.months),           { x: colX[2], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(r.gross.toLocaleString(),   { x: colX[3], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(r.tax.toLocaleString(),     { x: colX[4], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(r.pension.toLocaleString(), { x: colX[5], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(hebrewForPdf(r.pensionFund),{ x: colX[6], y, font: hebrewFont, size: 9, color: TEXT_COLOR });
      });
      const totalGross   = rows.reduce((s, r) => s + r.gross, 0);
      const totalTax     = rows.reduce((s, r) => s + r.tax, 0);
      const totalPension = rows.reduce((s, r) => s + r.pension, 0);
      const totalsY = 725 - rows.length * 16 - 10;
      overflow.drawText("Totals:",                      { x: colX[2], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
      overflow.drawText(totalGross.toLocaleString(),    { x: colX[3], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
      overflow.drawText(totalTax.toLocaleString(),      { x: colX[4], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
      overflow.drawText(totalPension.toLocaleString(),  { x: colX[5], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
    }

    const pdfBytes = await pdfDoc.save();
    const buffer   = Buffer.from(pdfBytes.buffer as ArrayBuffer);

    const mode = calibrate ? "calibration" : "final";
    console.log(`[form-1301] ${mode} ${buffer.byteLength}B — drawn=${drawn.length} missing=${missing.length}`);
    if (missing.length) console.log(`[form-1301] codes not in map: ${missing.join(", ")}`);

    if (!calibrate) {
      void auditLog({
        uid: ctx.uid,
        requestId: ctx.requestId,
        action: "form_1301_generated",
        metadata: { bytes: buffer.byteLength, drawn: drawn.length, missing: missing.length },
      });
    }

    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type":        "application/pdf",
        "Content-Disposition": `attachment; filename="form_1301_${mode}.pdf"`,
        "Content-Length":      String(buffer.byteLength),
        "Cache-Control":       "no-store",
        "X-PDF-Mode":          "overlay-field-mapped",
        "X-PDF-Pages":         String(pageCount),
        "X-PDF-Drawn":         String(drawn.length),
        "X-PDF-Missing":       String(missing.length),
      },
    });

  } catch (err: unknown) {
    console.error("[form-1301] Generation failed:", err);
    return internalError(
      "יצירת ה-PDF נכשלה. נסה שוב מאוחר יותר.",
      err instanceof Error ? err.message : String(err),
    );
  }
}

// Auth + rate-limit gate. Closes F-1, F-2, F1.2.6.
export const POST = withUser(
  withRateLimitForUser(handle, { prefix: "generate-form-1301", limit: 30 }),
);
