/**
 * POST /api/generate/form-1301 — Field-code-mapped PDF overlay
 *
 * Form 1301 (2025) is a 4-page static PDF. Coordinates come from
 * `templates/maps/1301_2025.json`, auto-generated by
 * `scripts/build-field-map.mjs` — see the form-135 route for full
 * architecture commentary and the 135_1301 generation task.md spec.
 *
 * Pass { "calibrate": true } to overlay red `→key:code` labels for
 * visual verification.
 */

import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, PDFFont, StandardFonts, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import fs from "fs";
import path from "path";
import { buildForm1301Fields, hebrewForPdf, assertForm1301Consistency } from "@/lib/pdfUtils";
import { isValidTZ } from "@/lib/validateTZ";
import { loadFieldMap, findField, type FieldMap } from "@/lib/fieldMap";
import { withUser } from "@/lib/api/withUser";
import { withRateLimitForUser } from "@/lib/api/withRateLimit";
import {
  invalidInput,
  invalidInputFromZod,
  internalError,
  serviceUnavailable,
} from "@/lib/api/errorEnvelope";
import { Form1301PayloadSchema } from "@/lib/api/schemas/generate";

const FORM_ID       = "1301_2025";
const TEMPLATE_PATH = path.join(process.cwd(), "public/templates/form1301_2025.pdf");
const FONT_TTF      = path.join(process.cwd(), "public/fonts/Assistant-Regular.ttf");
const FONT_WOFF     = path.join(process.cwd(), "public/fonts/Assistant-Regular.woff2");

const TEXT_COLOR = rgb(0.05, 0.2, 0.7); // readable navy blue
const CAL_COLOR  = rgb(0.9, 0, 0);

interface FieldDraw {
  key:     string;
  text:    string;
  code:    string;
  column?: string | null;
  size?:   number;
  heb?:    boolean;
  align?:  "right" | "left";
}

export async function POST(req: NextRequest): Promise<Response> {
  if (!fs.existsSync(TEMPLATE_PATH)) {
    return Response.json(
      { error: "TEMPLATE_MISSING", message: "form1301_2025.pdf not found at public/templates/" },
      { status: 503 },
    );
  }

  try {
    const body = (await req.json()) as Form135Payload & { calibrate?: boolean };
    const { taxpayer, financials } = body;

    if (!taxpayer || !financials) {
      return Response.json({ error: "Missing taxpayer or financials" }, { status: 400 });
    }
    if (taxpayer.idNumber && !isValidTZ(taxpayer.idNumber)) {
      return Response.json(
        { error: "INVALID_TZ", message: "מספר תעודת זהות לא תקין — ספרת ביקורת שגויה" },
        { status: 400 },
      );
    }

    const calibrate = !!body.calibrate;

    const map: FieldMap = loadFieldMap(FORM_ID);
    const pdfDoc = await PDFDocument.load(fs.readFileSync(TEMPLATE_PATH), { ignoreEncryption: true });

    const pageCount = pdfDoc.getPageCount();
    if (pageCount < 4) {
      return NextResponse.json(
        {
          error: "TEMPLATE_INVALID",
          detail: `Form 1301 template has ${pageCount} pages (expected 4). Replace public/templates/form1301_2025.pdf.`,
        },
        { status: 500 },
      );
    }

    pdfDoc.registerFontkit(fontkit);
    const fontPath   = fs.existsSync(FONT_TTF) ? FONT_TTF : FONT_WOFF;
    const hebrewFont = await pdfDoc.embedFont(fs.readFileSync(fontPath), { subset: false });
    const latinBold  = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const latinReg   = await pdfDoc.embedFont(StandardFonts.Helvetica);

    console.log(
      `[form-1301] template=${path.basename(TEMPLATE_PATH)} pages=${pageCount} ` +
      `map_codes=${Object.keys(map.fields).length} calibrate=${calibrate}`,
    );

    const vals = buildForm1301Fields(taxpayer, financials);

    const issues = assertForm1301Consistency(vals);
    if (issues.length > 0) {
      console.warn("[form-1301] page 1/3 deduction mismatch:", issues);
      if (calibrate) {
        return NextResponse.json({ error: "DEDUCTION_MISMATCH", issues }, { status: 422 });
      }
    }

    // ── Draw-list — one entry per field code (+ optional column) ──────────────
    const draws: FieldDraw[] = [
      // Personal (page 1 ID row, page 2-3 details)
      { key: "taxpayerId278", text: vals["012"],               code: "278", size: 10, align: "right" },
      { key: "spouseId277",   text: vals["013"],               code: "277", size: 10, align: "right" },
      { key: "idPersonal",    text: vals["012"],               code: "012", size: 10, align: "right" },
      { key: "lastName",      text: hebrewForPdf(vals["032"]), code: "032", size: 10, heb: true, align: "left" },
      { key: "city",          text: hebrewForPdf(vals["022"]), code: "022", size: 10, heb: true, align: "left" },
      { key: "street",        text: hebrewForPdf(vals["023"]), code: "023", size: 10, heb: true, align: "left" },
      { key: "houseNumber",   text: vals["024"],               code: "024", size: 10, align: "right" },

      // Employment — main vs 2nd employer (center vs left column, same codes)
      { key: "grossSalaryMain", text: vals["158_main"],        code: "158", size: 11, align: "right" },
      { key: "grossSalary2nd",  text: vals["172_2nd"],         code: "172", size: 11, align: "right" },
      { key: "taxWithheldMain", text: vals["068_main"],        code: "068", size: 11, align: "right" },
      { key: "taxWithheld2nd",  text: vals["069_2nd"],         code: "069", size: 11, align: "right" },
      { key: "pensionMain",     text: vals["258_main"],        code: "258", size: 10, align: "right" },
      { key: "severance",       text: vals["272"],             code: "272", size: 10, align: "right" },

      // Business
      { key: "bizIncomeMain", text: vals["201"],               code: "201", size: 11, align: "right" },
      { key: "bizIncome2nd",  text: vals["301"],               code: "301", size: 11, align: "right" },

      // Capital gains
      { key: "capitalGainRight",  text: vals["060"],           code: "060", size: 11, align: "right" },
      { key: "capitalGainCenter", text: vals["211"],           code: "211", size: 11, align: "right" },
      { key: "capitalLoss",       text: vals["067"],           code: "067", size: 11, align: "right" },
      { key: "foreignTaxCode157", text: vals["157"],           code: "157", size: 10, align: "right" },
      { key: "foreignTaxCode055", text: vals["055_1301"],      code: "055", size: 10, align: "right" },
      { key: "otherIncome",       text: vals["141"],           code: "141", size: 10, align: "right" },

      // Deductions — page 1
      { key: "donations",       text: vals["078"],             code: "078", size: 10, align: "right" },
      { key: "lifeInsurance",   text: vals["126"],             code: "126", size: 10, align: "right" },
      { key: "indPension",      text: vals["142"],             code: "142", size: 10, align: "right" },
      { key: "totalDeductions", text: vals["335"],             code: "335", size: 10, align: "right" },

      // Deductions — page 3/4 (ITA cross-check)
      { key: "lifeInsP3",          text: vals["036_p3"],       code: "036", size: 10, align: "right" },
      { key: "pensionDeductionP3", text: vals["045_p3"],       code: "045", size: 10, align: "right" },
      { key: "donationsP3",        text: vals["037_p3"],       code: "037", size: 10, align: "right" },

      // Bank details
      { key: "bankNumber",    text: vals["274"],               code: "274", size: 10, align: "right" },
      { key: "branchNumber",  text: vals["273"],               code: "273", size: 10, align: "right" },
      { key: "accountNumber", text: vals["044"],               code: "044", size: 10, align: "right" },
    ];

    const pageHeight = map.page_size.height;
    const drawn: { key: string; code: string; page: number }[] = [];
    const missing: string[] = [];

    for (const d of draws) {
      if (!d.text || d.text === "0") continue;

      const field = findField(map, d.code, d.column);
      if (!field) {
        missing.push(`${d.key}(${d.code})`);
        continue;
      }

      const page = pdfDoc.getPage(field.page - 1);
      const font: PDFFont = d.heb ? hebrewFont : latinBold;
      const size = d.size ?? 10;

      const yBaseline = pageHeight - field.value_box.y_bottom + 2;
      let x = field.value_box.x_left + 2;
      if ((d.align ?? "right") === "right") {
        const width = font.widthOfTextAtSize(d.text, size);
        x = field.value_box.x_right - width - 2;
      }

      try {
        page.drawText(d.text, { x, y: yBaseline, font, size, color: TEXT_COLOR });
        drawn.push({ key: d.key, code: d.code, page: field.page });
      } catch (e) {
        console.warn(`[form-1301] field "${d.key}"(${d.code}): ${e instanceof Error ? e.message : e}`);
      }

      if (calibrate) {
        try {
          page.drawText(`→${d.key}:${d.code}`, {
            x: field.value_box.x_left, y: yBaseline + size + 1,
            font: latinReg, size: 6, color: CAL_COLOR,
          });
        } catch { /* non-critical */ }
      }
    }

    // ── Tax-year header overlay ───────────────────────────────────────────────
    if (vals.taxYear) {
      const page1 = pdfDoc.getPage(0);
      page1.drawRectangle({ x: 191, y: 816, width: 42, height: 14, color: rgb(1, 1, 1), borderWidth: 0 });
      page1.drawText(vals.taxYear, { x: 193, y: 820, font: latinBold, size: 10, color: TEXT_COLOR });
    }

    // ── Multi-employer overflow sheet (3+ secondary employers) ────────────────
    const secondaryEmployers = (taxpayer.employers ?? []).filter((e) => !e.isMainEmployer);
    if (secondaryEmployers.length >= 2) {
      const overflow = pdfDoc.addPage([595.275, 841.89]);
      const rows = secondaryEmployers.map((e, i) => ({
        idx: i + 2,
        name: e.name ?? "",
        months: e.monthsWorked ?? 0,
        gross: e.grossSalary ?? 0,
        tax: e.taxWithheld ?? 0,
        pension: e.pensionDeduction ?? 0,
        pensionFund: e.pensionFundName ?? "",
      }));
      overflow.drawText(hebrewForPdf("פירוט מעסיקים נוספים — נספח לטופס 1301"),
        { x: 60, y: 800, font: hebrewFont, size: 14, color: TEXT_COLOR });
      overflow.drawText(
        `Tax year: ${vals.taxYear}   |   ID: ${vals["012"] || "-"}`,
        { x: 60, y: 780, font: latinReg, size: 10, color: TEXT_COLOR },
      );
      const colHeaders = ["#", "Name", "Months", "Gross (ILS)", "Tax (ILS)", "Pension (ILS)", "Pension Fund"];
      const colX = [60, 90, 260, 310, 380, 450, 520];
      colHeaders.forEach((h, ci) => {
        overflow.drawText(h, { x: colX[ci], y: 745, font: latinBold, size: 9, color: TEXT_COLOR });
      });
      rows.forEach((r, ri) => {
        const y = 725 - ri * 16;
        overflow.drawText(String(r.idx),              { x: colX[0], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(hebrewForPdf(r.name),       { x: colX[1], y, font: hebrewFont, size: 9, color: TEXT_COLOR });
        overflow.drawText(String(r.months),           { x: colX[2], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(r.gross.toLocaleString(),   { x: colX[3], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(r.tax.toLocaleString(),     { x: colX[4], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(r.pension.toLocaleString(), { x: colX[5], y, font: latinBold, size: 9, color: TEXT_COLOR });
        overflow.drawText(hebrewForPdf(r.pensionFund),{ x: colX[6], y, font: hebrewFont, size: 9, color: TEXT_COLOR });
      });
      const totalGross   = rows.reduce((s, r) => s + r.gross, 0);
      const totalTax     = rows.reduce((s, r) => s + r.tax, 0);
      const totalPension = rows.reduce((s, r) => s + r.pension, 0);
      const totalsY = 725 - rows.length * 16 - 10;
      overflow.drawText("Totals:",                      { x: colX[2], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
      overflow.drawText(totalGross.toLocaleString(),    { x: colX[3], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
      overflow.drawText(totalTax.toLocaleString(),      { x: colX[4], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
      overflow.drawText(totalPension.toLocaleString(),  { x: colX[5], y: totalsY, font: latinBold, size: 9, color: TEXT_COLOR });
    }

    const pdfBytes = await pdfDoc.save();
    const buffer   = Buffer.from(pdfBytes.buffer as ArrayBuffer);

    const mode = calibrate ? "calibration" : "final";
    console.log(`[form-1301] ${mode} ${buffer.byteLength}B — drawn=${drawn.length} missing=${missing.length}`);
    if (missing.length) console.log(`[form-1301] codes not in map: ${missing.join(", ")}`);

    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type":        "application/pdf",
        "Content-Disposition": `attachment; filename="form_1301_${mode}.pdf"`,
        "Content-Length":      String(buffer.byteLength),
        "Cache-Control":       "no-store",
        "X-PDF-Mode":          "overlay-field-mapped",
        "X-PDF-Pages":         String(pageCount),
        "X-PDF-Drawn":         String(drawn.length),
        "X-PDF-Missing":       String(missing.length),
      },
    });

  } catch (err: unknown) {
    console.error("[form-1301] Generation failed:", err);
    return Response.json(
      { error: "PDF_GENERATION_FAILED", detail: err instanceof Error ? err.message : String(err) },
      { status: 500 },
    );
  }
}
